### ISSUE TITLE
Login/Register Form Task List (Init:0,02,26,22) 

### ISSUE THREAD

**Issue by RechtDev** [RechtDev/JtsAutoShopWebProject#3]
Login form should have

- [ ] Email input field with required
- [ ] password input field
- [ ] remember me button
- [ ] form should match color scheme of website
