### ISSUE TITLE
Customer View page Task List (Init:0,02,26,22) 

### ISSUE THREAD

**Issue by RechtDev** [RechtDev/JtsAutoShopWebProject#4]
Customer View Page should have:

- [ ] ability to look at tickets in a panel separated by active or canceled
- [ ] ability to see quick details about service request but should have ability to open to see full details.
- [ ] ability to cancel tickets
- [ ] ability to edit tickets (just the date to come in)
- [ ] button to create new tickets
- [ ] slide menu should have a button for customers details 
- [ ] slide menu should have a button for signing out.
