### ISSUE TITLE
Technician Dashboard Task List (Init:2.0,02,26,22) 

### ISSUE THREAD

**Issue by RechtDev** [RechtDev/JtsAutoShopWebProject#5]
Tech Dashboard should have:

- [ ] ability to see all tickets
- [x] side menu > button to take them to see just their tickets
- [x] sorting by date, car type
- [x] buttons that allow transfer, cancel
